### ISSUE TITLE
BLE on ESP32-C3-MINI-1-N4-A  AWS Express Link

### ISSUE THREAD

**Issue by mra59** [espressif/esp-aws-expresslink-eval#14]
Hello, is there any way to switch between behavior like BLE and like Express Link in ESP32-C3-MINI-1-N4-A modules?
Can modules answer to all the AT commands of the two behaviours?
Kind regards
Mauro Righetto

**Comment by dhavalgujar** [comment]
Hi @mra59,
BLE support is available in the [v2.5.0](https://github.com/espressif/esp-aws-expresslink-eval/releases/tag/v2.5.0) release.
