### ISSUE TITLE
Cannot update OTAcertificate in AWS IoT ExpressLink (ESP32-C3-AWS-ExpressLink-DevKit)

### ISSUE THREAD

**Issue by mikeanny** [espressif/esp-aws-expresslink-eval#16]
I used command AT+CONF OTAcertificate=pem

and paste certificate info

but got response :

ERR21 INVALID OTA UPDATE

and the following logs

I (1302613) CONF: Writing OTAcertificate[0]
I (1302613) CONF: Reading OTAcertificate[0]
I (1302613) CONF: -----> PEM

If I used command AT+CONF? OTAcertificate pem

I got the response

OK1 pem
PEM

And the following logs

I (1535193) CONF: Reading OTAcertificate[0]
I (1535203) CONF: -----> PEM

Looks like OTAcertificate is read-only not writable? Is there any way to write or erase the data of OTAcertificate? I tried to OTW the firmware on both v1.0.20 and v2.4.1 but the OTAcertificate doesnt change

**Comment by dhavalgujar** [comment]
Hi @mikeanny,
Apologies for the delay in getting back to you.

Please try upgrading to [v2.4.5](https://github.com/espressif/esp-aws-expresslink-eval/releases/tag/v2.4.5) or [v2.5.0](https://github.com/espressif/esp-aws-expresslink-eval/releases/tag/v2.5.0) using OTW.
That should fix this issue for you.
