### ISSUE TITLE
AT+TIME? returning incorrect date (wrong month)

### ISSUE THREAD

**Issue by nwilding** [espressif/esp-aws-expresslink-eval#21]
Hello, I have been prototyping with an ESP32-C3-AWS-ExpressLink-DevKit V1.0, without updating any firmware. When I issue the AT+TIME? command on 2023/10/01 (October 1st) it returned the time with a date of 2023/09/01 (September 1st). I tried again on the 2nd of the month and got similar results. I assume there's an issue with the code in the ESP express link where it's returning the incorrect date. As I mentioned, I have not updated firmware on the device, so possibly this has already been identified and corrected?

**Comment by Kriechi** [comment]
Fixed in the latest release from November 2022:
https://github.com/espressif/esp-aws-expresslink-eval/releases/tag/v2.4.1
